language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - EXTRA_REMOTES=". git+https://github.com/gfngfn/satysfi-external-repo.git"
  - PACKAGE="satyrographos-repo-test"
  matrix:
  - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi.0.0.3+dev2019.11.16
    satyrographos=0.0.2.2
    satysfi-class-exdesign
    satysfi-class-exdesign-doc
    satysfi-class-stjarticle
    satysfi-class-stjarticle-doc
    satysfi-base
    satysfi-fonts-dejavu
    satysfi-fonts-dejavu-doc
    satysfi-fonts-theano
    satysfi-fonts-theano-doc
    satysfi-grcnum
    satysfi-grcnum-doc
    satysfi-matrix
    satysfi-matrix-doc
    satysfi-zrbase
    satysfi-dist"
  - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi
    satyrographos=0.0.1.7
    satysfi-class-stjarticle
    satysfi-siunitx
    satysfi-zrbase
    satysfi-dist"
  - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi-dist.0.0.4 satysfi.0.0.4"
# We do not have develop snapshot yet.
# - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi-dist.0.0.3+dev2019.11.16 satysfi.0.0.3+dev2019.11.16"
os:
  - linux
