language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PRE_INSTALL_HOOK="export OPAMERRLOGLEN=0 OPAMVERBOSE=1 OPAMSTATS=1 ; echo PreInstallHook Test"
    - EXTRA_REMOTES=". git+https://github.com/gfngfn/satysfi-external-repo.git"
    - PACKAGE="satyrographos-repo-test"
  matrix:
  # Stable version
  - OCAML_VERSION=4.06
    PACKAGE="satyrographos-repo-test-stable"
  # Develop version
  - OCAML_VERSION=4.09
    PACKAGE="satyrographos-repo-test-develop"
os:
  - linux
cache:
  - $HOME/.opam/archives
  - $HOME/.opam/download-cache
# vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=4 :
