language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - EXTRA_REMOTES=". git+https://github.com/gfngfn/satysfi-external-repo.git"
    - PACKAGE="satyrographos-repo-test"
    - >-
      PACKAGES_FOR_STABLE="
      satysfi-base
      satysfi-cancel
      satysfi-class-exdesign
      satysfi-class-exdesign-doc
      satysfi-class-stjarticle
      satysfi-class-stjarticle-doc
      satysfi-class-slydifi
      satysfi-enumitem
      satysfi-fonts-asana-math
      satysfi-fonts-asana-math-doc
      satysfi-fonts-computer-modern-unicode
      satysfi-fonts-computer-modern-unicode-doc
      satysfi-fonts-dejavu
      satysfi-fonts-dejavu-doc
      satysfi-fonts-noto-emoji
      satysfi-fonts-noto-sans
      satysfi-fonts-noto-sans-doc
      satysfi-fonts-noto-sans-cjk-jp
      satysfi-fonts-noto-sans-cjk-jp-doc
      satysfi-fonts-noto-serif
      satysfi-fonts-noto-serif-doc
      satysfi-fonts-noto-serif-cjk-jp
      satysfi-fonts-noto-serif-cjk-jp-doc
      satysfi-fonts-theano
      satysfi-fonts-theano-doc
      satysfi-grcnum
      satysfi-grcnum-doc
      satysfi-matrix
      satysfi-matrix-doc
      satysfi-zrbase
      "
    - PACKAGES_FOR_DEVELOP="$PACKAGES_FOR_DEVELOP"
  matrix:
  # Stable version
  - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi.0.0.4
    satysfi-dist
    satyrographos=0.0.2.3
    $PACKAGES_FOR_STABLE"
  # Develop version
  - OCAML_VERSION=4.06 EXTRA_DEPS="satysfi.0.0.4+dev2020.02.22
    satysfi-dist
    satyrographos=0.0.2.3
    $PACKAGES_FOR_STABLE"
os:
  - linux
cache:
  - $HOME/.opam/archives
  - $HOME/.opam/download-cache
# vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=4 :
